services:
  nginx-proxy:
    container_name: nginx-proxy-filesapi
    image: jwilder/nginx-proxy:alpine
    restart: 'always'
    depends_on:
      - filesapi
    ports:
      - "8081:8081"
    volumes: # Volumes usados para fazer o proxy reverso, a config para rodar os sites ao mesmo tempo $      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./nginx/nginx.d:/etc/nginx/conf.d/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  filesapi:
    container_name: filesapi
    image: edumss/filesapi:latest
    restart: 'always'
    ports:
      - "8082:8082"
    volumes: 
      - "/home/eduardo/projetos/FilesAPI/Arquivos:/app/files"
